// <auto-generated />
namespace EventManager.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ManyToManyEv_ApUsr : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ManyToManyEv_ApUsr));
        
        string IMigrationMetadata.Id
        {
            get { return "201611301918275_ManyToManyEv_ApUsr"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
